[project]
name = "ignr"
version = "0.1.0"
description = "Quickly fetch .gitignore templates"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "inquirerpy>=0.3.4",
    "requests>=2.34.2",
    "typer>=0.27.1",
]

[project.scripts]
ignr = "ignr.main:app"

[build-system]
requires = ["uv_build>=0.11.23,<0.12.0"]
build-backend = "uv_build"
